<?php

require_once __DIR__ . '/../src/MiniPDF.php';

use MiniPDF\MiniPDF;

$html = '
    <h1 style="text-align: center; color: #003366;">MiniPDF Showcase Document</h1>

    <div style="background-color: #f0f0f0; padding: 10px; margin-bottom: 20px;">
        <p>This document demonstrates the core capabilities of the <b>MiniPDF</b> library, a lightweight and dependency-free PHP solution for PDF generation.</p>
    </div>

    <h2>Text Styling & Layout</h2>
    <p>MiniPDF supports a variety of text formatting options:</p>
    <ul>
        <li><b>Bold text</b> using &lt;b&gt; or &lt;strong&gt;</li>
        <li><i>Italic text</i> using &lt;i&gt; or &lt;em&gt;</li>
        <li><u>Underlined text</u> using &lt;u&gt;</li>
        <li><span style="color: #ff0000;">Colored text</span> via inline CSS</li>
        <li><span style="background-color: #ffff00;">Highlighted text</span> via background-color</li>
    </ul>

    <p style="text-align: right; font-style: italic;">
        Right-aligned text with italic style.
    </p>

    <h2>Table Support</h2>
    <p>Tables are rendered with automatic column width distribution and support for cell-level styling:</p>

    <table style="width: 100%;">
        <tr style="background-color: #333333; color: #ffffff;">
            <th>Feature</th>
            <th>Support</th>
            <th>Details</th>
        </tr>
        <tr>
            <td>HTML5 Parsing</td>
            <td style="color: #00aa00; font-weight: bold;">Yes</td>
            <td>Uses PHP DOMDocument</td>
        </tr>
        <tr>
            <td>CSS Styles</td>
            <td style="color: #00aa00; font-weight: bold;">Yes</td>
            <td>Inline styles supported</td>
        </tr>
        <tr>
            <td>Word Wrapping</td>
            <td style="color: #00aa00; font-weight: bold;">Yes</td>
            <td>Handles long text within cells automatically</td>
        </tr>
        <tr>
            <td>Dependencies</td>
            <td style="color: #ff0000; font-weight: bold;">No</td>
            <td>100% Pure PHP</td>
        </tr>
    </table>

    <h2>Advanced Wrapping</h2>
    <p>Our line breaking engine ensures that even very long paragraphs are wrapped correctly according to the page margins. This is essential for generating readable reports and documents that contain substantial amounts of text content. It handles spaces correctly and ensures that words are not broken mid-way, providing a professional look to your generated PDF files.</p>

    <div style="margin-top: 50px; text-align: center; font-size: 10px; color: #777777;">
        <hr>
        Generated by MiniPDF v1.1
    </div>
';

$minipdf = new MiniPDF($html);
$pdfBinary = $minipdf->render();

file_put_contents(__DIR__ . '/sample.pdf', $pdfBinary);

echo "Showcase sample PDF generated at examples/sample.pdf\n";
