<?php

require_once __DIR__ . '/../src/MiniPDF.php';

use MiniPDF\MiniPDF;

$html = '
    <h1 style="color: #ff0000; text-align: center;">MiniPDF Library</h1>
    <h2 style="color: #0000ff;">Features:</h2>
    <p>1. <b>No dependencies</b> - Pure PHP 8.x</p>
    <p>2. <b>HTML5 Parsing</b> - Uses DOMDocument</p>
    <div style="text-align: right; color: #555555; font-size: 10px;">
        Generated by MiniPDF v1.0
    </div>
    <div style="margin-top: 20px;">
        <p>Support for <i>inline</i> styles:</p>
        <p>
            <span style="color: #ff00ff;">Magenta</span>,
            <span style="color: #00ffff;">Cyan</span>,
            <span style="color: #ffff00; font-size: 20px;">Yellow Large</span>
        </p>
    </div>
    <h3 style="text-align: center; color: #00aa00;">Basic PDF 1.7 Spec</h3>
    <p style="text-align: justify;">
        This library manually assembles the PDF structure including the catalog, pages,
        content streams, and the cross-reference table.
    </p>
';

$minipdf = new MiniPDF($html);
$pdfBinary = $minipdf->render();

file_put_contents(__DIR__ . '/output_complex.pdf', $pdfBinary);
echo "Complex PDF generated at examples/output_complex.pdf\n";
